name: PMD Analysis

on:
  push:
    branches:
      - master
  pull_request:
    branches:
      - master

jobs:
  check:
    runs-on: ubuntu-latest

    steps:
      - name: Checkout code
        uses: actions/checkout@v4

      - name: Set up JDK 17
        uses: actions/setup-java@v4
        with:
          java-version: "17"
          distribution: "temurin"
          cache: "maven"
      - run: mvn com.spotify.fmt:fmt-maven-plugin:check
      - name: Run PMD
        run: |
          curl -LO https://github.com/pmd/pmd/releases/download/pmd_releases%2F7.11.0/pmd-bin-7.11.0.zip
          unzip pmd-bin-7.11.0.zip 
          ./pmd-bin-6.47.0/bin/run.sh pmd -d . -R rulesets/java/quickstart.xml -f text
